### PR TITLE
Add export class

### PR DESCRIPTION
**Pull request by kenoir**

### CODE REVIEW

**Comment by kenoir** [comment]
@stevenjack just needed to keep the parent element.

**Comment by stevenjack** [comment]
Parent? I see you just need to pass the whole last evaluated hash through,
nice.

On Tuesday, September 16, 2014, Robert Kenny notifications@github.com
wrote:

> @stevenjack https://github.com/stevenjack just needed to keep the
> parent element.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stevenjack/dynamodb-exporter/pull/1#issuecomment-55793272
> .

## 

_Steven Jack_
t:+44 (0) 7811963038e:stevenmajack@gmail.comt:
http://twitter.com/stevenjack85in:http://uk.linkedin.com/in/stevenjack

Steven Jack Ltd, 36 FFF, Elder Avenue, N88PS. Registered Address:  Unit 11,
Hove Business Centre, Fonthill Road, Hove, East Sussex, BN3 6HA, United
Kingdom. Registered in England & Wales No. 08008948. VAT registration
number 131658716.

**Comment by stevenjack** [comment]
Ah yes got you, the CLI that'll take the parameters and consume this class. Guess we merge this then I'll create another PR for that?

**Comment by kenoir** [comment]
@stevenjack yarp.

**Pull request closed without merging**
